### ISSUE TITLE
Food Forest Commons

### ISSUE THREAD

**Issue by usama9500** [commons-stack/commonsprize#1]
## Nomination video link

[![image](https://user-images.githubusercontent.com/96994784/166879027-185d2163-feb4-4a4b-86dc-a52ac20803ef.png)](https://www.youtube.com/watch?v=jgQidcWykrE&list=PLy6j39s17_jRWYm2vd0XS8qXolCIekSEJ&index=7)

## Tell us about the community that you are nominating
AgroforestDAO is using web3 tools to incentivize training for new food forest stewards. Initially coordinating for learning and building human capacity so that later we can coordinate for food and wood entrepreneurship glocally. Build onchain frameworks for tracking, credentials, recognition, inventories, and retirement plans. IRL contracts using land lease for agroforestry with short, mid and long term design.

## What public goods does this community support or will they support in the future?
knowledge, technical capacity, bioregional genetic bank, intergenerational natural resources and supply chains

## Who are the people, DAOs, and other organizations already part of this community?
We are coordinating in a telegram group with folks coming from web3 background (Kernel Community), and agroforestry background (Syntropic Learning Community - Australia, Europe, Americas and Africa)

## Why do you think this community needs a Commons?
Because by opting into a role in this common narrative people will be able to follow a common seasonal harvests' agenda and to plan for leaving natural goods legacies to their next generations. In a way very similar to the ancestral narratives, but with a Web3 touch.

## What other resources do you have that will make your Commons deployment a success? 
We are preparing a NFT collection with royalties to raise funds to run a MVP training in Brazil. Mentors and apprentices in the MVP will share monthly journals that will be minted as NFTs, put on sale and generate royalties to a common fund. If we are successful on it we plan on launching new trainings and NFTs use cases for funding and governance. We are still not clear if we should launch a community ERC-20 token or use some already existent one (like Giveth for example).

## Do you have an idea for the name of this Commons?
Food Forest Commons.

## Submitted by [Discord handle or Twitter handle]
Discord handle: DiogoJ#2058
Twitter Handle: @DiogoJo61288106

**Comment by Jose5048** [comment]
There could be significant Economic Returns in this initiative. Please see this comment of mine in the context of Precious Plastics : https://github.com/commons-stack/commonsprize/issues/33#issuecomment-1134352206

**Comment by usama9500** [comment]
The issue has been closed as the first round has concluded! 🙌
