### ISSUE TITLE
Underground DAO

### ISSUE THREAD

**Issue by usama9500** [commons-stack/commonsprize#11]
## Tell us about the community that you are nominating
Our goal is to provide alternative methods for funding science through our community-driven platform. Our focus is on the underground ecosystem and soils with the goal of collaborating with these natural systems to protect and improve our shared environment. In pursuit of this goal, we will work closely with mission-aligned organisations with a particular focus on opportunities that tend to be overlooked by current methods of funding. 

Our goal is to accelerate and amplify the impact of Focused Research Organisations and other science-driven organisations by identifying topics and technologies that are key to their mission but may fall outside their scope of effort. To identify relevant opportunities, we will necessarily partner closely with these organisations. For our launch partner, we have selected SPUN | Society for the Protection of Underground Networks, an organisation that we have helped to incubate and develop since its inception, and which has received funding for its core science from the Grantham Foundation and Schmidt Foundation.

The opportunities we will develop through the platform fall into the following broad categories:

- Science that crosses or falls between the boundaries of disciplines, such as the interaction between fungal networks and their bacterial counterparts
- Communities or methods that tend to be overlooked by mainstream science, such as how traditional agricultural practices impact underground network diversity
- Projects that are science-adjacent, such as the representation of fungal networks and ecosystems through technologies such as augmented reality or sound
- Proposals that are too nascent or speculative to be incorporated into the organisational roadmap but which show potential long-term promise, such as network sensing through electrical signal analysis
- Grants to enable underserved communities to participate in underground science, such as students, artists, or local organisations.

## What public goods does this community support or will they support in the future?
This community consists of scientists and entrepreneurs who focus on  fungal and microbial soil ecosystem with the goal of creating new methodologies for collaboration with these underground system actors in pursuit of common goals (such as long-term ecosystem survival)

## Who are the people, DAOs and other organizations already part of this community?
The science is being led by SPUN.earth, which is a focused research organisation being incubated by btheory.ventures--a collective focused on finding new ways to combat climate change

## Why do you think this community needs a Commons?
Our goal for the commons is to create an alternative model for funding early-stage, moonshot science that decentralizes access to capital and coordinates diverse communities of supporters.

We propose creating a SPUN DAO [= collaboration + funding + decision-making] to explore projects that support, are adjacent to, or build upon the core science.

The value for our science partner--SPUN.Earth--includes increased cultural relevance, an alternative source of philanthropic support, and a mechanism for capturing commercial value.

## What other resources do you have that will make your Commons deployment a success? 
- SPUN has secured 3 years of funding for the core science from the Grantham and Schmidt foundations
- We have a web3 lead assigned to support the project
- We have identified additional investments for the DAO program

## Do you have an idea for the name of this Commons?
Underground DAO

## Submitted by [Discord handle or Twitter handle]
Discord: flaneur#6084	
Twitter: @jasoncremerius

**Comment by Jose5048** [comment]
Please take a look at this comment https://github.com/commons-stack/commonsprize/issues/33#issuecomment-1134352206

**Comment by usama9500** [comment]
The issue has been closed as the first round has concluded! 🙌
