### ISSUE TITLE
Unmonopolizable Therapies Commons

### ISSUE THREAD

**Issue by usama9500** [commons-stack/commonsprize#15]
[![image](https://user-images.githubusercontent.com/96994784/166665697-80695313-169f-415a-8a42-5940bf95f7b3.png)](https://www.youtube.com/watch?v=40UeWLDutYo&list=PLy6j39s17_jRWYm2vd0XS8qXolCIekSEJ&index=5)

## Tell us about the community that you are nominating
Empowering and transforming patient communities around public goods medicines is the vision and mission driving Crowd Funded Cures (CFC). 

CFC is an integral part of the overall DeSci community and our mission is to develop an open-source platform that drives a circular (token)economy around clinical trial organizations, investors and healthcare payers to fund the clinical development of public goods medicines, i.e., unmonopolizable therapeutics, including repurposed generics, plant medicine, and other treatment regiments that cannot be developed under the current patent system, by using pay-for-success contracts and Open Source Pharma NFTs. The CFC platform will help patient communities identify, fund and generate clinically meaningful data of unmonopolizable therapies via RCT trials (or other suitable, regulated trial methods) in which that data may be incorporated into an "Open Source Pharma IP-NFT". 

With our model and the supporting feasibility study, we plan to demonstrate that repurposed generics, plant medicine, and other unmonopolizable therapeutics will save costs for healthcare payers and governments in a financially robust manner.

## What public goods does this community support or will they support in the future?
90% of US prescriptions are off-patent generic drugs, and method of use patents cannot prevent off-label use by doctors. Therefore, new uses for off-patent drugs are non-rivalrous and non-excludable public goods that lack financial incentives for funding clinical trials under the patent system. 

What if pharma was incentivized by patient outcomes, rather than patents? That's what we are planning to achieve through Crowd Funded Cures' platform to crowdfund Open-Source Pharma NFT bounties.

## Who are the people, DAOs and other organizations already part of this community?
We are building a community-driven approach to drug development and opening up funding, innovation, and market access by partnering with other DeSci projects like VitaDAO (longevity therapeutics R&D) and Molecule GmbH (IP-NFT marketplace) as well as collaborating with other synergistic web3 projects such as labDAO (web3 contract research organization (CRO) marketplace), PsyDAO (psychedelics research), and "Copyleft Cultivars, a mission-aligned non-profit developing a copyleft license for plant genetics who have also submitted a nomination for the Commons Prize to launch the Open Cultivars Commons (https://github.com/commons-stack/commonsprize/issues/31) and others as a coalition, to bring biomedical research incentives into the 21st century by aligning private incentives with public good.

We've already secured a $40k USD grant from VitaDAO as part of that partnership for a feasibility study and fundraising with other mission-aligned organizations, including the Open Source Pharma Foundation.

## Why do you think this community needs a Commons?
As mentioned above, new methods of use for off-patent drugs are non-excludable and non-rivalrous public goods, which means that a PFS contract incentive to fund clinical trials to discover such new uses has open source "baked in". It is also possible for participants to agree to make their products available to the community at low cost by using "patentleft" licensing terms as a condition for receiving outcome payments under a PFS contract. Being organised as a Commons will help facilitate our goal of establishing a scalable open source business model and ensure that members are mission-aligned. Operating as a DeSci project is also consistent with becoming a Commons.

## What other resources do you have that will make your Commons deployment a success? 
We have already secured $40k from VitaDAO and are are partnering with other nonprofits and for-profit organizations in the field to drive these PFS programs forward (see Feasibility Study funding proposal here: https://docs.google.com/document/d/1PDkFlwYhW-7MEEdMU1i31lR8RjYDJFvDUsNGLo5mlO4/edit#). 

We are also conducting a pre-seed SAFT round with a value of $500k USD with half committed. 

We are currently raising a $1Mn USD Payer Fund, to support a longevity generic drug repurposing clinical trial by Dr. Brad Stanfield as a pilot IP-NFT x PFS contract in partnership with the Longevity Prize (https://twitter.com/longevityprize).

## Do you have an idea for the name of this Commons?
Unmonopolizable Therapies Commons

## Submitted by [Discord handle or Twitter handle]
Discord: Savva Kerdemelidis#9857, Nick FIORΞNZA#8698
Twitter: @CrowdFundedCure, @nfiorenza

**Comment by Jose5048** [comment]
"Unmonopolizable Therapies Commons" Really? As a name? But great project and IMO you do not need funding from Common Stack, but the eco system participation. **This initiative has to succeed**.

**Comment by crowdfundedcures** [comment]
> 

😆 It's not the easiest name to pronounce but does explain the problem; the phrase "unmonopolisable therapies" (e.g. repurposed generic drugs, supplements, diets and lifestyle interventions) comes from our founder Savva Kerdemelidis' 2014 Masters thesis, which proposed the use of flexible prizes to overcome the tragedy of commons (https://ir.canterbury.ac.nz/handle/10092/9826). It falls within a broader category of "unprofitable therapies". 

Perhaps better to call it Crowd Funded Cures Commons? Our intention is to launch this year as an impact DAO. 

We would like to participate in the Common Stack ecosystem as we see lots of synergies with our idea to bring open source business models to biopharma (although some funding to help us scale would also be very helpful :) 

Thanks so much for your support ! ❤️🦾

**Comment by usama9500** [comment]
The issue has been closed as the first round has concluded! Incredible cause 🙌
