### ISSUE TITLE
Breadchain Commons

### ISSUE THREAD

**Issue by usama9500** [commons-stack/commonsprize#17]
[![image](https://user-images.githubusercontent.com/96994784/167774877-18c9b063-d841-4214-95c4-92cd3e120fa6.png)](https://www.youtube.com/watch?v=lMHA429UVTc&list=PLy6j39s17_jRWYm2vd0XS8qXolCIekSEJ&index=25)

## Tell us about the community that you are nominating
Breadchain is a collective of decentralized cooperative projects exploring blockchain for progressive causes.

## What public goods does this community support or will they support in the future?
Breadchain supports the cooperative economy on the blockchain. The propagation of cooperatives is a public good that benefits those who want to practice commons based organization.

## Who are the people, DAOs and other organizations already part of this community?
PactDAO, LaborDAO, Basid Network, LeftDAO

## Why do you think this community needs a Commons?
This community needs a commons for having an appropriate governance structure for handling and allocating the shared resources if all of the stakeholders part of the network.

## What other resources do you have that will make your Commons deployment a success? 
The Breadchain Crowdstaking Protocol is planned to be released soon. We view it as the main engine for funding post-capitalist projects.

## Do you have an idea for the name of this Commons?
Breadchain Commons

## Submitted by [Discord handle or Twitter handle]
Discord: Theblockchainsocialist#5005
Twitter: @tbsocialist

**Comment by Jose5048** [comment]
This seems to a fairly straightforward application of Web 3 technology, and it does have the potential to create a Commons of its own. But in what sense is it unique, which may be an unfair question considering how cutting edge and nascent this whole area is. Yet another project deserving of funding at first glance IMO.

**Comment by usama9500** [comment]
The issue has been closed as the first round has concluded!🙌
