### ISSUE TITLE
All for Climate DAO

### ISSUE THREAD

**Issue by usama9500** [commons-stack/commonsprize#18]
[![image](https://user-images.githubusercontent.com/96994784/167161269-3464c7d6-ff3c-4a04-8816-6b9e04cc806f.png)](https://www.youtube.com/watch?v=sfGSZ8a4D_k&list=PLy6j39s17_jRWYm2vd0XS8qXolCIekSEJ&index=12)

## Tell us about the community that you are nominating
 All for Climate DAO, a community that is building and maintaining a common infrastructure for grassroots citizen initiatives.

## What public goods does this community support or will they support in the future?
The environment and local regenerative communities: The community is already supporting more than 150 grassroots collectives of active citizens all over Europe, some in Africa. The collectives are all working on projects related to climate and social justice. Some of them have community gardens or plant trees, some occupy buildings, some do activism and some do community building. It is a very diverse network of citizens, rooted locally, but connected via All for Climate.

## Who are the people, DAOs and other organizations already part of this community?
Frederic Laloux (we partnered to help him raise funds for his new documentary on the climate emergency called The WEEK), Gitcoin (partnered with them for GR12-13-14 climate), Regens Unite (sub DAO), BanklessDAO (partnering for Regens Unite)

Besides the collectives, we have a steady team of about 8 people in the DAO, taking different roles. We work closely with Gitcoin on the climate rounds (GR 12 and 13, and organising GR14 right now). We have connections with ReFiDAO, whose funds we are going manage within All for Climate (via the common infrastructure). We are organising a conference in May, RegensUnite, where we invite to full network, bridging worlds and organisations.

## Why do you think this community needs a Commons?
Climate justice activists are pioneers but they need help. They need common resources, infrastructures, tools, to organize and build up new islands of sanity for #DeepAdaptation in every neighborhood.

All for Climate wants to become the Greenpeace of 21st century, a fully transparant, decentralised network of autonomous collectives.  For that we need:  a common treasury managed by and for the community to give easy access to funding, a common legal and administrative infrastructure (already partly existing) to remove burdens from citizens so they can get started asap, without delay. It makes no sense  for active citizens to go through all the pain themselves; a common infrastructure, managed as a common, will help them do what we all need: a system change with many many successful active citizens.  We need to build the infrastructure that makes it possible for citizens to bring commoning and community building (locally) back to the center of there lives. This includes a reward system for contributing, so being an active citizens does not need to be hobby like it is now. Active citizens are a public good, we need to nurture them, reward them, involve them. We are all depending on them.

## What other resources do you have that will make your Commons deployment a success? 
We raised $20k as part of multiple gitcoin grants, we have a steady income of $1-2k/month through the fiscal host we are running https://opencollective.com/allforclimate for 150+ local action groups / collectives, that have themselves raised more than €800k by ~2000 donors https://dao.allforclimate.earth/results

We have some external funding and the collectives that we support pay a tiny fee for the services. I am myself experienced in communing IRL and other people in our community are too. All for Climate is a healthy non profit for two years now, but we need to include the new tools an possibilities that web3 is offering. We need to become a common.

## Do you have an idea for the name of this Commons?
All for Climate DAO

## Submitted by [Discord handle or Twitter handle]
Discord handles: xdamman#3734, Leen#8610	

Twitter handles: @xdamman, @leen_schelfhout

**Comment by Jose5048** [comment]
Is there any way this initiative can become self sustaining? Especially with the Web3 token mechanisms that are there? Its emeinently feasible IMO.

**Comment by usama9500** [comment]
The issue has been closed as the first round has concluded! Incredible cause, a great initiative taken by All for Climate DAO 🙌
