### ISSUE TITLE
KERNEL Commons

### ISSUE THREAD

**Issue by usama9500** [commons-stack/commonsprize#23]
[![image](https://user-images.githubusercontent.com/96994784/167863918-f96a7e11-7ac1-4ac6-8fac-9b7c03369d8f.png)](https://www.youtube.com/watch?v=qw5evelhp_c&list=PLy6j39s17_jRWYm2vd0XS8qXolCIekSEJ&index=28)

## Tell us about the community that you are nominating
KERNEL (https://kernel.community)

## What public goods does this community support or will they support in the future?
KERNEL is a lifelong, educational, and intentional community of care.

KERNEL as Public Good
Any meaningful shift, within self or society, begins with how we learn and teach.

Valuable knowledge may present itself for free, but it must be given attention, intention, and reflection in order to become personally meaningful. It is this paradox which makes educational gifts the seed around which a community crafting new value models can flourish: “a single flower blooms, and throughout the world it is spring”.

Enter KERNEL: a trust space for talented individuals to use Web 3 as a means to explore their humanity more holistically. KERNEL begins with a KERNEL “Block”: an 8 week experience, anchored by 16 lessons which is filled by 250 interested, talented, and diverse peers.

The topics in a KERNEL block transcend web3 - starting with trust, moving through meaning and value, and eventually ending in giving and scale-ability.

These (free and open-source) lessons provide fertile ground for an eight week experience which is ultimately co-created by the KERNEL Fellows who interact with 1) the content and 2) each other. A deepening of personal spirit and the relationships KERNEL Fellows form with each are the primary orientations of the program.

KERNEL aims to be a living example of what it means to live well together. The experience provides questions, not answers, as we explore: how can we build better lives for ourselves as we build a better web for us all?

KERNEL Fellows are builders at leading web3 companies as founders, dancers, technologists, gamers, economists, designers, artists, and musicians. They deeply enjoy each others company and transcend these distinctions every time we meet them again.

## Who are the people, DAOs and other organizations already part of this community?
Amongst many other (immeasurable) contributions, KERNEL Fellows have gone on to start 100+ web3 projects which have raised a combined $200MM. We hope they all consider what it will mean to lead a ‘community of care’ in their own context.

All are talented individuals exploring what’s next for our internet culture. All care deeply about one another. All are genuinely interested in exploring themselves, first, in order to build a better web. Many of them contribute to KERNEL as guides, mentors, investors, and most importantly listeners who care.

A smattering of stories and ways to speak about the KERNEL Fellows & their projects include the following:

EPNS: Harsh and Richa participated in Genesis Block, eventually raising funding and launching the Ethereum notifications protocol. EPNS also went on to be a Gitcoin Grants matching funder in GR12 and GR13. At KERNEL, wealth only means “having enough to share”, so we are delighted to see Fellows giving back as they become wealthier. It is the ultimate feedback loop.
Toucan: johnx25bd participated in Genesis Block, met Raph and James in KB3 when he was a steward, who he joined to build infrastructure for carbon markets. Toucan 1 is also giving back to ongoing Gitcoin Grants rounds.
Myco 2: Co-founders Arya and Mark met at KERNEL Expo Week (!) in Genesis Block. They have built tools for co-ownership of communities.
Sherlock: Jack joined after starting Sherlock at HackMoney and spent great time in the Token Communities guild, led by the IDEO team (Reuben and Joe). IDEO later participated in Sherlock’s fundraise. The DeFi insurance project now has $100MM TVL.
Verses: Jasmine Wang, Kelsey Chen, Daanish Shabbir, and others explored both interdependence and the pluriverse 1 artifacts alongside us in KB4. They also joined as fireside guests, including Jasmine alongside Vitalik in KB5.
For more information on KERNEL projects and people, see here 2.

Here is a smattering of additional context:

KERNEL alumni include Alex Masmej (Showtime), Mara Schmeidt (Coinbase), Amy Jung (MakerDAO), Rebecca Mqamelo (Zerion), Chase Chapman (TryCrypto), Matt Stephenson (P1anck), Shreyas Hariharan (Llama), Tess Rinearson (Twitter), and Niran Babalola (Panvala).
25+ companies have raised funding after going through KERNEL, including EPNS, Swivel Finance, Pods Finance, Charged Particles, Mintgate, Showtime, Spectral Finance, Reach, Chaos Labs, Yup, EthBlockArt, Coinvise, Llama, Akropolis, Verto Exchange, and many more.
A variety of GitcoinDAO contributors have been with us in KERNEL including @lanitrock, @krrisis @sidcode, @michelle_ma, @linht.tran, Ben Percifield, Tanaya Vikrant, Maxwell Kanter, and others.
Educational backgrounds of KERNEL Alumni include: Harvard, Stanford, MIT, Yale, Oxford, Penn, IITs, BITS Pilani, Princeton, UC Berkeley, Cambridge, and Texas A&M
KERNEL Fellows come from a variety of skilled backgrounds, including Meta, the United Nations (including a diplomat), Twitch, Coinbase, Facebook, the Ethereum Foundation, and The US Federal Reserve.
Within Web3, KERNEL Fellows are meaningful contributors to Ethereum, Uniswap, Gitcoin, Showtime, MakerDAO, Celo, Cosmos, Avalanche, Solana, Binance, Coinbase, Gemini, Optimism, Opyn, Metamask, ConsenSys, Filecoin, and a variety of other incredible projects
Over the past 2 years, KERNEL has grown into a web3 commons with customs co-created by 1,200 unique, incredible and diverse human beings.

These people (and many more in our hearts) make up KERNEL. They care for each other, and participate in the peer-to-peer experience that is web3, knowing that KERNEL is a space for them to give and receive. They also help us welcome new blocks, and they know KERNEL is there for them into perpetuity.

## Why do you think this community needs a Commons?
The next phase of KERNEL is aligned with a Commons. This is described in the following governance posts-

- https://gov.gitcoin.co/t/kernel-evolves-a-new-leaf-for-gitcoin-dao/9912

This mutualistic co-evolution of KERNEL in its interdependent journey with other Commons is aligned with the mission of education and lifelong building in web3. We will be experimenting with many ideas for tokens which enable perpetual scholarships, help in decentralized schooling, and encourage communities of care. These are described in - https://kernel.community/en/blog/community/free-learn/
https://gitcoin.co/grants/4307/deschool
https://www.youtube.com/watch?v=qw5evelhp_c

## What other resources do you have that will make your Commons deployment a success? 
We were supported by Gitcoin Holdings in our initial journey from Blocks 1-5. We are currently in the process of spinning out and becoming a foundation. To that end, we are fundraising from mutually aligned web3 organizations. One of these efforts can be found here- 

https://gov.gitcoin.co/t/s14-proposal-amended-kernel-budget-request/10444

We have contributors but will need to coordinate with our existing projects to help deploy a Commons. This will need to be discussed with The Commons Stack and TEC.

## Do you have an idea for the name of this Commons?
KERNEL Commons

## Submitted by [Discord handle or Twitter handle]
Discord: sidcode#1729	
Twitter: @sidcode_

**Comment by tamarandom** [comment]
GM all! 

We have a new development to share!

KERNEL is withdrawing their submission for the Commons Prize. They are focused on immediate fund raising and that would be in conflict with an effort to deploy a Commons over the next 9 months. We are big fans of KERNEL and will help support their goals in any way we can!

What this means for the the Prize is that the KERNEL nomination issue will be closed and anyone that voted for them will receive their voting power back. If you are one of the many that voted for KERNEL, you can now recast your votes! 

Just over 48 hours left to ROCK THE VOTE!
