### ISSUE TITLE
Banting DAO

### ISSUE THREAD

**Issue by usama9500** [commons-stack/commonsprize#24]
[![image](https://user-images.githubusercontent.com/96994784/167777369-93b177c4-170a-4bd8-b86a-2e5ef46389e1.png)](https://www.youtube.com/watch?v=R38YCbseTV0&list=PLy6j39s17_jRWYm2vd0XS8qXolCIekSEJ&index=27)

## Tell us about the community that you are nominating
This community is large and made up of people with insulin dependent diabetes. We have a huge problem that has been fought for many many years and still has no solution: Intellectual property hold-up resulting in exorbitant pricing for medications (insulin) and technology (cgms, insulin pumps, etc).  The community is organized and right now works hard to help patients with no access to insulin ( who are dying ) to get them the required medication to continue being alive. This community has people from all walks of like and we all know that these conditions will not change unless we do something about that: 1. Fight to regulate or liberate intellectual property and pricing. 2. Coordinate to help people in desperate need of medication.

## What public goods does this community support or will they support in the future?
Intellectual property for diabetes related medications ( mainly insulin ) and technologies ( including open source software and hardware ).

## Who are the people, DAOs and other organizations already part of this community?
There is a large community of people on Twitter: #insulin4all and #wearenotwaiting ... I am working on creating a discord server where we all can organize our initiatives.

## Why do you think this community needs a Commons?
We need a way to organize and create value in the form of common goods that can be exchanged for money to execute the projects and activities related to the community objectives. All activities right now depend on voluntary personal donations.

## Do you have an idea for the name of this Commons?
Banting DAO ( name comes from Frederick Banting who discovered insulin and sold the patent for $1 dollar so every person with type I diabetes in the world could quickly get access to the medication )

## Submitted by [Discord handle or Twitter handle]
Discord: bustavo#8085, Mount Manu#3530
Twitter: @bustavo,  @mount_manu

**Comment by tamarandom** [comment]
Bustavo has asked to withdraw this nomination for BantingDAO. 

Closing this issue.
