### ISSUE TITLE
Impact(NFT) Commons

### ISSUE THREAD

**Issue by usama9500** [commons-stack/commonsprize#26]
[![image](https://user-images.githubusercontent.com/96994784/168237399-886cebd3-d4f8-4bfb-bbb9-6257f2669740.png)](https://www.youtube.com/watch?v=p8ebnZTH5PM)

## Tell us about the community that you are nominating
ImpactNFT Alliance

## What public goods does this community support or will they support in the future?
The Alliance supports work of 40+ member web3 groups and 20 senior advisors to drive impact in the drive for support of 17 Sustainability Development Goals, currently have already driven thousands of individuals and millions of dollars to social impact

## Who are the people, DAOs and other organizations already part of this community?
Members can be found at impactNfT.org, here are a few: Earth.org, Enrex, Altry, Snarky Sharks, WildCards, EthicHub, AfricaRare (Africa's first metaverse), Agent Green, BridgeTheGap, Voiz (largest student climate action DAO), Mammalz (experience nature), Kowloon King (culture icon for HK on pop culture), and 30+ more organizations

## Why do you think this community needs a Commons?
We already have sizable impact in our own local communities but we see ourselves as pioneering the model, with WWF Panda Labs, of creating “Ostram DAOs” to encode the key ideas of Ostroms common gatherings into smart contract code and making sure that actors can behave with good guard rails. Ultimately we are creating natural capital endowments and we need common tools to govern this

## What other resources do you have that will make your Commons deployment a success? 
We are proud to have amazing supporters and advisors who are helping make the Alliance sustainable: including Jason Hsu, Senior Research Fellow at The Ash Center for Democratic Governance and Innovation, Harvard Kennedy School and Visiting Research Fellow at Department of Politics and International Relations (DPIR) at University of Oxford, formerly Crypto Congressman, Jason served as Legislator At-Large in Taiwan’s national parliament from 2016 to 2020. A selection of achievements during his tenure include setting up the Asia Blockchain Alliance (ABA), Taiwan Parliamentary Coalition for Blockchain (TPCB), founding the Indo-Pacific Cybersecurity Alliance and initiating the several key legislations such as the FinTech Regulatory Sandbox Act, Amendment on Anti-Money Laundering Law, Cybersecurity Management Act and Virtual Currency Guidelines (Security Token Offerings), Artificial Intelligence Development Act. Katherine Foster, Executive of The Open Earth Foundation where she leads collaborations with the UNFCCC Global Innovation Hub. A former diplomat specializing in human security and climate, Katherine has been spearheading innovation at the nexus of technology, policy and sustainable development for 30 years. She has held leadership roles at Climate-KIC (Europe’s largest Climate Innovation Initiative) Katherine is a member of the EU Blockchain Observatory, the BIS Digital Green Bond Project Genesis, and the ESMA FISC Working Groups. Cyrus Hodes is a Partner at FoundersX Ventures, a cross-stage Silicon Valley VC firm. He is a co-founder of Duckweed Bio, a Florida- based Agtech/Climate Tech startup. Cyrus co-founded and chaired the AI Initiative at The Future Society, a think tank incubated at Harvard Kennedy School. He served as Advisor to the Minister of AI at the UAE Prime Minister's Office. Pedro Robledo Web3 Strategist Experienced Public Affairs and Communications advisor with +13 years of experience in the public and private sector. Pedro advises different tech startups in the smart city and web 3 space. Former National Secretary of Civic Organizations and Youth of the Republic of Argentina. The full list can be found here:

## Do you have an idea for the name of this Commons?
Impact(NFT) Commons

## Submitted by [Discord handle or Twitter handle]
Discord: MetaMaximus#9821	
Twitter: Pericarus

**Comment by tamarandom** [comment]
Update: Video from an event that the alliance held.

--- 

[![image](https://user-images.githubusercontent.com/703624/168239014-cc508b21-6814-4aa8-9b3f-4effcee858a8.png)](https://youtu.be/EAALbeNJ288)]

**Comment by usama9500** [comment]
The issue has been closed as the first round has concluded! Incredible cause 🙌
