### ISSUE TITLE
ReCommon

### ISSUE THREAD

**Issue by usama9500** [commons-stack/commonsprize#34]
[![image](https://user-images.githubusercontent.com/96994784/167265966-e6453d07-2e51-42bf-9309-1142a9a72c2d.png)](https://www.youtube.com/watch?v=QXGHbQ5Xxlk&list=PLy6j39s17_jRWYm2vd0XS8qXolCIekSEJ&index=18)

## Tell us about the community that you are nominating
Regenerative Community Land Trust

## What public goods does this community support or will they support in the future?
Bioregional land commons reclamation & stewardship platform for ongoing management of said commons.

## Who are the people, DAOs and other organizations already part of this community?
RegenCLT (RegenCLT.org) and our active membership, ReCommon (ReCommon.io), Anna-Marie Swan, Todd Youngblood, Center for CLT Innovation (Charlie Fisher)

## Why do you think this community needs a Commons?
On the digital side, the land stewardship platform we are building is intended to be a tool for people all over the world, and as such we want the technology and platform itself to be a commons owned by the member community that uses and benefits from it. On the physical side, we are creating open-source legal templates for the formation of bioregional community land trusts to support regenerative community development. We've joined forced with ReCommon to ensure that the technical stewardship platform as a commons is built for and perfectly syncs up with the physical commons and land stewardship communities that RegenCLT works with. Essentially, we are building the tools and scalable framework to integrate Ostram's principles for managing a commons into the appropriate technology to help land stewardship communities effectively manage a physical commons. We believe the tech stack should be a commons too.

## What other resources do you have that will make your Commons deployment a success? 
Our core team and network consists of land stewards, community builders and regenerative farmers that have all been obsessively thinking about the technical solutions to facilitate the emergence of regenerative communities for years. As such, our approach is grounded in real-life experience of what it means to steward a piece of land and to live in community. Because of that real-life, hands-in-the-dirt experience we are uniquely suited to deploy this Commons in a way that actually helps people on the ground based on their real needs, not just theory. This seems to be particularly needed in the ReFi and tech commons space, where many of the ideas stay in the high-tech conceptual realm and are inaccessible to the actual communities on the ground that are intended to benefit from them. The funding we have received thus far is minimal, mainly from membership dues and a few small donations.

## Do you have an idea for the name of this Commons?
At this point, we're calling the commons that is the stewardship platform 'ReCommon'. The analog counterpart to that digital commons is 'RegenCLT'.

## Submitted by [Discord handle or Twitter handle]
Discord: Alex | RegenCLT#0174	
Twitter: @arcorren / @regenclt

**Comment by Jose5048** [comment]
What would be the model for a) economic viability of this initiative and then b) the financial viability. IMO it almost certainly economically viable and then the financial viability follows almost naturally. And then the token mechanism and economics.

**Comment by usama9500** [comment]
The issue has been closed as the first round has concluded! 🙌
