### ISSUE TITLE
Liberating Structures Commons

### ISSUE THREAD

**Issue by usama9500** [commons-stack/commonsprize#5]
[![image](https://user-images.githubusercontent.com/96994784/167293336-e7ff7e32-2c95-46c1-897e-93537e1e053f.png)](https://www.youtube.com/watch?v=vkiN0OwpbpI&list=PLy6j39s17_jRWYm2vd0XS8qXolCIekSEJ&index=22)

## Tell us about the community that you are nominating
The Liberating Structures(LS) community is organized around learning and practicing a set of communication tools known as LS. There 200 local user groups spread across the globe, hosting several opportunities to learn per week.

## What public goods does this community support or will they support in the future?
There are two meaningful public goos worth mentioning. The first is that the toolkit themselves are public goods published under Creative Commons Attribution-NonCommercial-ShareAlike Copyright. The second is the Learning Impact Network that is the community core activities of teaching others to use these tools for Shared Thinking them through practice.

## Who are the people, DAOs and other organizations already part of this community?
As of this moment there are 8,857 members of the General channel of the LS Slack community. This group is a completely Decentralized Autonomous Organization, there is no legal entity, there is no non-profit, there is a book of practices and a bunch of people who use them, two of whom are the authors of the book, Keith McCandless and Henri Lipmanowicz.

GravityDAO has been hosting an LS practice group in the TEC and these tools are being included in the upcoming Graviton Training which will begin in May.

- Jeremy Nathaniel Akers(me)
- Fisher Qua (Back-Loop Consulting)
- Arvind Singhal (Professor, UTEP)
- Nancy White (Full Circle)
- Curt Lindberg (PartnersInComplexity)
- Liz Rykert (MetaStrategies, Toronto)
- June Holley (Smart Networks)
- Michael Gardam, MD (University Health Network)
- Kevin Buck (Emergent Success)
- David Gasser (Photographer)
- Monique Sternin (Positive Deviance co-founder)
- Neil McCarthy (Principal, McCarthy Consulting)
- Tim Jaasko-Fisher, JD (University of Washington)
- Anna Jackson (Alpinista Consulting, Austin TX)
- Dan Pesut (Professor, University of Minnesota)
- Sharon Benjamin (Alchemy Consulting) 
- Narrative sensemaking with Spryng 
- Richard Bartlett of Enspiral, the Humm and Microsolidarity is an LS user. 
- Stefan Morales and Susan Basterfield of Greater Than
- Elise Keith of Lucid Meetings
- Barry Overeem and Christiaan Verwijs of The Liberators
- David Heath London, UK
- Johannes Schartau of Holisticon

## Why do you think this community needs a Commons?
On one hand you could argue that a commons is not necessary. Off of the strength of nothing but a set of practices that work to help include and unleash all voices, with no clear path to a business model, in less than 10 years there are almost 10000 practitioners. On the other, I would argue that we have an opportunity for perhaps the greatest experiment in the history  retroactive funding for public goods. With the resources that a Commons could provide the people that have been already doing the work for free may do more of it, or not, the only way to find out is to run the experiment and see if Ethers Phoenix works the way we hope.

## What other resources do you have that will make your Commons deployment a success? 
Liberating Structures are tools for Shared Thinking. Which means that for all of the questions around deploying a Commons, we have native tools in our cultural build that can help us answer them at scale.

## Do you have an idea for the name of this Commons?
Liberating Structures Commons

## Submitted by [Discord handle or Twitter handle]
Discord: Jeremy&TheGospelOfChange#8201
Twitter: @gospelofchange

**Comment by Jose5048** [comment]
Its the same thing I am telling others for their initiatives. There will certainly be a quantifiable Economic Impact which will translalte into Financial Returns which can be tokenised making this initiative self sustaining. And grow.

**Comment by usama9500** [comment]
The issue has been closed as the first round has concluded! 🙌
